# Auto-generated by QCC-IDE
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

set target-async on
target extended-remote :3333

set history filename gdb_history.log
set history save on
set print pretty on
set pagination off
set output-radix 16
set remotetimeout unlimited
