# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: Apache-2.0;
manifest:
  remotes:
    - name: upstream
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/upstream
    - name: qoss
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/qoss
    - name: 3rdparty
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/3rdparty
    - name: prop
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/prop
    - name: zephyrproject-rtos
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
    revision: main
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: kernel.qzephyr.2.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - zcbor      # for c++ programming
    - name: cmsis_6
      remote: zephyrproject-rtos
      revision: cmsis_6.qzephyr.2.0
      path: modules/hal/cmsis_6
    - name: cAT
      remote: 3rdparty
      revision: 3rdparty.qzephyr.1.0
      path: modules/lib/cAT
    - name: mbedtls
      remote: zephyrproject-rtos
      revision: mbedtls.qzephyr.2.0
      path: modules/crypto/mbedtls
    - name: hostap
      remote: zephyrproject-rtos
      revision: hostap.qzephyr.2.0
      path: modules/lib/hostap
    - name: littlefs
      remote: zephyrproject-rtos
      revision: littlefs.qzephyr.2.0
      path: modules/fs/littlefs
    - name: segger
      remote: zephyrproject-rtos
      revision: segger.qzephyr.2.0
      path: modules/debug/segger
    - name: qapp
      remote: qoss
      revision: qcc730.qzephyr.2.0
    - name: qhal
      remote: upstream
      revision: qcc730.qzephyr.2.0
      path: modules/hal/qcom
    - name: libpowerqcc730
      remote: prop
      revision: qcc730.qzephyr.2.0
      path: prop/libpowerqcc730
    - name: libwifiqcc730
      remote: prop
      revision: qcc730.qzephyr.2.0
      path: prop/libwifiqcc730
    - name: libsensorqcc730
      remote: prop
      revision: qcc730.qzephyr.2.0
      path: prop/libsensorqcc730
    - name: libcryptoqcc730
      remote: prop
      revision: qcc730.qzephyr.2.0
      path: prop/libcryptoqcc730
  self:
    west-commands: zephyr/scripts/west-commands.yml
