# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: Apache-2.0;
manifest:
  remotes:
    - name: upstream
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/upstream
    - name: qoss
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/qoss
    - name: prop
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/prop
    - name: zephyrproject-rtos
      url-base: ssh://review-android.quicinc.com:29418/qzephyr/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
    revision: main
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: kernel.qzephyr.1.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-blocklist:
          - net-tools # Network tools for testing with Qemu
    - name: cmsis
      remote: zephyrproject-rtos
      revision: cmsis.qzephyr.1.0
      path: modules/hal/cmsis
    - name: mbedtls
      remote: zephyrproject-rtos
      revision: mbedtls.qzephyr.1.0
      path: modules/crypto/mbedtls
    - name: qapp
      remote: qoss
      revision: qapp.qzephyr.1.0
    - name: qhal
      remote: upstream
      revision: hal.qhal.1.0
      path: modules/hal/qualcomm
    - name: libpowerqcc730
      remote: prop
      revision: libpowerqcc730.qhal.1.0
      path: prop/libpowerqcc730
    - name: libwifiqcc730
      remote: prop
      revision: libwifiqcc730.qhal.1.0
      path: prop/libwifiqcc730
    - name: libsensorqcc730
      remote: prop
      revision: libsensorqcc730.qhal.1.0
      path: prop/libsensorqcc730
    - name: libcryptoqcc730
      remote: prop
      revision: libcryptoqcc730.qhal.1.0
      path: prop/libcryptoqcc730
  self:
    west-commands: zephyr/scripts/west-commands.yml
